# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      cache_key:
        description: "Cache key"
        required: true
        type: string
      image_name:
        description: "Repository short name"
        required: true
        type: string
      in_memory:
        description: "Use in-memory docker"
        required: false
        type: boolean
        default: false
      in_memory_docker_size:
        description: "Use in-memory docker"
        required: false
        type: number
        default: 2
      in_memory_workdir_size:
        description: "Use in-memory docker"
        required: false
        type: number
        default: 1

      dockerfile:
        description: "Dockerfile path"
        required: false
        type: string
        default: "./docker/dockerfile.production"
      context:
        description: "Build context path"
        required: false
        type: string
        default: "."
      platform:
        description: "Target platform"
        required: false
        type: string
        default: ""
      image_tag:
        description: "Override image tag"
        required: false
        type: string
      build-args:
        required: false
        type: string
        default: ""
    secrets:
      IMG_REGISTRY:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, heavy, "${{ inputs.platform }}"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #  moby/buildkit:local
      - name: copy buildkit
        if: ${{ inputs.in_memory }}
        run: docker save moby/buildkit:local > /tmp/buildkit.tar

      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        if: ${{ inputs.in_memory }}
        with:
          tmpfs_size: ${{ inputs.in_memory_workdir_size }}
          swap_size: 4
          swap_location: "/mnt/swapfile"

      - name: copy buildkit
        if: ${{ inputs.in_memory }}
        run: docker load < /tmp/buildkit.tar

      - name: mount current folder in RAM
        run: sudo mount -t tmpfs -o size=${{ inputs.in_memory_workdir_size }}g tmpfs $(pwd)
        if: ${{ inputs.in_memory }}

      - run: |
          REF_NAME=${REF_NAME##*/}
          echo "REF_NAME=$REF_NAME" >> $GITHUB_OUTPUT
        id: ref_name
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.4

      - name: Build Docker image for ${{ inputs.platform }}
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ inputs.platform }}
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          push: true
          load: false
          build-args: |
            IMG_REGISTRY=${{ secrets.IMG_REGISTRY }}
            ${{ inputs.build-args }}
          labels: |
            branch=${{ steps.ref_name.outputs.REF_NAME }} 
            sha=${{ github.sha }}
          tags: |
            ${{ secrets.IMG_REGISTRY }}/${{ inputs.image_name }}:${{ steps.ref_name.outputs.REF_NAME }}_${{ github.sha }}-${{ inputs.platform }}
            ${{ secrets.IMG_REGISTRY }}/${{ inputs.image_name }}:${{ inputs.image_tag || format('{0}-{1}-{2}', github.sha, github.run_id, github.run_attempt) }}-${{ inputs.platform }}
          cache-from: |
            type=registry,ref=${{ secrets.IMG_REGISTRY }}/${{ inputs.image_name }}-cache:${{ steps.ref_name.outputs.REF_NAME }}-${{ inputs.platform }}
            type=registry,ref=${{ secrets.IMG_REGISTRY }}/${{ inputs.image_name }}-cache:develop-${{ inputs.platform }}
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ secrets.IMG_REGISTRY }}/${{ inputs.image_name }}-cache:${{ steps.ref_name.outputs.REF_NAME }}-${{ inputs.platform }}
