# This is a basic workflow to help you get started with Actions

name: Deploy sourcemaps

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      cache_key:
        description: "Cache key"
        required: true
        type: string
      dockerfile:
        description: "Dockerfile path"
        required: false
        type: string
        default: "./docker/dockerfile.production"
      context:
        description: "Build context path"
        required: false
        type: string
        default: "."
    secrets:
      IMG_REGION:
        required: true
      CACHE_BUCKET:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    steps:
      - name: Build sourcemaps
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          push: false
          load: true
          tags: sourcemaps
          cache-from: type=s3,region=${{ secrets.IMG_REGION }},bucket=${{ secrets.CACHE_BUCKET }},name=${{ inputs.cache_key }}
          platforms: linux/amd64
          target: source_map
          build-args: |
            CI_COMMIT_SHA: ${{ github.sha }}

      - name: Publish sourcemaps
        shell: bash
        run: docker run --rm -e ROLLBAR_POST_SERVER_ITEM=${{ secrets.ROLLBAR_POST_SERVER_ITEM }} sourcemaps