# This is a basic workflow to help you get started with Actions

name: Deploy sourcemaps

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      cache_key:
        description: "Cache key"
        required: true
        type: string
      dockerfile:
        description: "Dockerfile path"
        required: false
        type: string
        default: "./docker/dockerfile.production"
      context:
        description: "Build context path"
        required: false
        type: string
        default: "."
      additional_tag:
        description: "Build context path"
        required: false
        type: string
        default: ""
    secrets:
      IMG_REGION:
        required: true
      CACHE_BUCKET:
        required: true
      ROLLBAR_POST_SERVER_ITEM:
        required: true
      MVN_USER:
        required: false
      MVN_PASSWORD:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    steps:
      - name: mount current folder in RAM
        run: sudo mount -t tmpfs -o size=1g tmpfs $(pwd)

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build sourcemaps
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          push: false
          load: true
          tags: sourcemaps
          cache-from: type=s3,region=${{ secrets.IMG_REGION }},bucket=${{ secrets.CACHE_BUCKET }},name=${{ inputs.cache_key }}
          target: source_map
          build-args: |
            MVN_USER=${{ secrets.MVN_USER }}
            MVN_PASSWORD=${{ secrets.MVN_PASSWORD }}
            NODE_AUTH_TOKEN=${{ secrets.MVN_PASSWORD }}
            CI_COMMIT_SHA=${{ github.sha }}${{ inputs.additional_tag }}
            ${{ inputs.build-args }}

      - name: Publish sourcemaps
        shell: bash
        run: docker run --rm -e ROLLBAR_POST_SERVER_ITEM=${{ secrets.ROLLBAR_POST_SERVER_ITEM }} sourcemaps
